# Generated by Django 3.1.1 on 2020-10-08 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coggle_key', models.CharField(max_length=300, null=True)),
                ('miro_key', models.CharField(max_length=300, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('about', models.CharField(max_length=400, null=True)),
                ('userData', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100, null=True)),
                ('service', models.CharField(max_length=30, null=True)),
                ('similarity', models.IntegerField(default=0)),
                ('plagiarism', models.IntegerField(default=0)),
                ('count_nodes', models.IntegerField(default=0)),
                ('count_first_layer_branches', models.IntegerField(default=0)),
                ('average_node_text', models.IntegerField(default=0)),
                ('max_height', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.task')),
            ],
        ),
    ]
