# Generated by Django 3.1.1 on 2020-10-07 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_auto_20201007_1954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='coggle_key',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='miro_key',
        ),
    ]
