# Generated by Django 3.1.1 on 2020-10-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_auto_20201007_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='coggle_key',
            field=models.CharField(default='Undefined', max_length=300),
        ),
        migrations.AddField(
            model_name='userdata',
            name='miro_key',
            field=models.CharField(default='Undefined', max_length=300),
        ),
    ]
