# Generated by Django 2.2.1 on 2019-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_homework_task_userdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='max_similarity',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='homework',
            name='plagiarism',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='homework',
            name='similarity',
            field=models.FloatField(default=-1),
        ),
    ]
