# Generated by Django 2.2.1 on 2019-05-13 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20190513_2346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='max_similarity',
        ),
        migrations.AddField(
            model_name='homework',
            name='link_true',
            field=models.CharField(default='-', max_length=100),
        ),
    ]
