# Generated by Django 2.2.1 on 2019-05-13 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20190514_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='link_true',
        ),
    ]
