# Generated by Django 2.2.1 on 2019-05-17 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190514_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='plagiarism',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='homework',
            name='similarity',
            field=models.FloatField(default=0),
        ),
    ]
